version: "3.7"
services:
  olx-monitor:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - OLX_URLS=${OLX_URLS}
      - CRON_INTERVAL=${CRON_INTERVAL:-*/5 * * * *}
      - UI_USERNAME=${UI_USERNAME}
      - UI_PASSWORD=${UI_PASSWORD}
    volumes:
      - ./data:/usr/data
